---
abstract: 'Simple worker support do jobs in parallel processes.'
author:
  - 'Night Sailer(Pan Fan) < nightsailer{at}gmail dot com >'
build_requires:
  ExtUtils::MakeMaker: 6.62
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.62
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Parallel-QueueWorker
no_index:
  directory:
    - inc
    - t
requires:
  Moose: 2.0401
  Moose::Object: 2.0401
  Parallel::ForkManager: 0
  Test::More: 0.98
  YAML::Any: 0.77
  feature: 1.16
  perl: 5.12.0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Parallel-QueueWorker
  homepage: http://search.cpan.org/dist/Parallel-QueueWorker
  license: http://dev.perl.org/licenses/
  repository: origin
version: 0.001
